apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: system-upgrade-app-set
  namespace: argocd
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: ocm-placement-generator
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: guestbook-app-placement
        requeueAfterSeconds: 30
  template:
    metadata:
      name: '{{name}}-system-upgrade'
      labels:
        apps.open-cluster-management.io/pull-to-ocm-managed-cluster: 'true'
      annotations:
        argocd.argoproj.io/skip-reconcile: 'true'
        apps.open-cluster-management.io/ocm-managed-cluster: '{{name}}'
        apps.open-cluster-management.io/ocm-managed-cluster-app-namespace: argocd
    spec:
      project: default
      source:
        repoURL: 'https://github.com/worawatwi/ocm-argocd-demo.git'
        targetRevision: HEAD
        path: upgrades
      destination:
        server: https://kubernetes.default.svc
        namespace: system-upgrade
      syncPolicy:
        automated:
          prune: true
        syncOptions:
          - CreateNamespace=true