apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: mci
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/open-cluster-management-io/multicloud-integrations.git
      revision: HEAD
      directories:
      - path: deploy/crds
      - path: deploy/controller
  template:      
    metadata:
      name: 'mci-{{index .path.segments 1}}'     
    spec:
      project: default
      source:
        repoURL: https://github.com/open-cluster-management-io/multicloud-integrations.git
        targetRevision: HEAD
        path: '{{.path.path}}'
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        syncOptions:
          - CreateNamespace=true  
        automated:
          prune: true
          selfHeal: true
      